include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    require_trailing_commas: true
    prefer_const_literals_to_create_immutables: false
